---
title: "Figure3 Generate simulated objects"
author: "Yuzhou Feng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## libraries
```{r, message=FALSE}
library(spaSim)
library(SPIAT)
```
## Simulations

The `spaSim` package provides default background images for users. 

The following simulations are based on `bg1` background image.

First, simulate separate tumour and immune clusters. Two clusters are closer 
and closer. A tumour cluster is simulated first.

```{r}
set.seed(610)
bg <- multiple_images_with_clusters(bg_sample = bg1, 
                                    cluster_shape = 2, 
                                    prop_infiltration = 0, 
                                    cluster_size = 200, 
                                    cluster_loc_x = -650, 
                                    cluster_loc_y = -450,
                                    plot_image = T)
# the above function returns a list; need to extract the first element as the image
bg <- bg[[1]] 

set.seed(610)
colo_imageL <- multiple_images_with_clusters(bg_sample = bg,
                                             cluster_shape = 3, 
                                             prop_infiltration = 0, 
                                             cluster_size = 300, 
                                             cluster_loc_x = c(100,-200,-400),
                                             cluster_loc_y = c(300, 0, -200),
                                             plot_image = T)
# name the images
for (i in 1: length(colo_imageL)){
    image <- colo_imageL[[i]]
    attr(image, "name") <- paste("Sim_colo", i, sep = "_")
    colo_imageL[[i]] <- image
}


# Second, simulate a tumour cluster with the same size 
# as the previous tumour clusters, with an immune ring.
set.seed(610)
colo_image_immuneR <- multiple_images_with_immune_rings(bg_sample = bg1,
                                                        cluster_size = 200,
                                                        ring_shape = 2,
                                                        prop_infiltration = 0,
                                                        ring_width = 80,
                                                        cluster_loc_x = 0,
                                                        cluster_loc_y = 0,
                                                        prop_ring_infiltration = 0)
colo_image_immuneR <- colo_image_immuneR[[1]]
attr(colo_image_immuneR, "name") <- "Sim_colo_4"
colo_imageL[[4]] <- colo_image_immuneR

# Last, simulate tumour clusters infiltrated with immune cells. With more and more immune cells.

set.seed(610) # for reproducibility
imageL <- multiple_images_with_clusters(bg_sample = bg1, 
                                        cluster_shape = 2, 
                                        prop_infiltration = c(0.1, 0.3, 0.5),
                                        cluster_size = 200, 
                                        cluster_loc_x = -650, 
                                        cluster_loc_y = -450)

# name the images
for (i in 1: length(imageL)){
    image <- imageL[[i]]
    j <- length(colo_imageL) + 1
    attr(image, "name") <- paste("Sim_colo", j, sep = "_")
    colo_imageL[[j]] <- image
}

for (i in 1:length(colo_imageL)){
    sce <- colo_imageL[[i]]
    plot_cell_categories(sce, c("Tumour","Immune","Others"), 
                         c("red", "darkgreen", "lightgray"),
                         feature_colname = "Cell.Type")
}

save(colo_imageL, file = "Objects/Figure3_simulated.Rda")

```

```{r Reproducibility}
sessionInfo()
```